"""
Bonus Task 2.2 — Adversarial Negation Robustness
Evaluates the base model and the fine-tuned model on a negated-hypothesis
dataset derived from Multi-NLI validation_mismatched.

The negation logic (from the original notebook):
  - Neutral examples (label == 1) are excluded — negating a neutral
    hypothesis has no well-defined gold label.
  - Entailment (0) → Contradiction (2) after negation.
  - Contradiction (2) → Entailment (0) after negation.

The negated dataset is generated by an LLM (NVIDIA API) and cached in
./data/negated_validation_set.xlsx.  If you already ran
negation_set_generation.py and have negated_validation_set.xlsx in the
project root, it is copied to ./data/ automatically.

Outputs:
  ./results/<MODEL_SLUG>/negation-baseline.xlsx
  ./results/<MODEL_SLUG>/negation-finetuned.xlsx
"""

import os
import shutil
import torch
import pandas as pd
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")


# ── Configuration ─────────────────────────────────────────────────────────────
BASE_MODEL_NAME  = "Qwen/Qwen3-1.7B"
# BASE_MODEL_NAME = "Qwen/Qwen3-0.6B"
MODEL_SLUG       = BASE_MODEL_NAME.split("/")[-1]
FINETUNED_DIR    = f"./models/{MODEL_SLUG}/final_model"

MAX_LENGTH       = 128
INFER_BATCH_SIZE = 16
NUM_SAMPLES      = None   # set to an int (e.g. 500) to limit; None = full file

DATA_DIR         = "./data"
RESULTS_DIR      = f"./results/{MODEL_SLUG}"
NEGATED_DATA_PATH = os.path.join(DATA_DIR, "negated_validation_set.xlsx")
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)

LABEL_MAP    = {0: "entailment", 1: "neutral", 2: "contradiction"}
INT_LABEL    = {v: k for k, v in LABEL_MAP.items()}
VALID_LABELS = set(LABEL_MAP.values())


# ── Load negated dataset ───────────────────────────────────────────────────────
# Check ./data/ first, then fall back to project root (from previous generation)
ROOT_COPY = "./negated_validation_set.xlsx"
if not os.path.exists(NEGATED_DATA_PATH) and os.path.exists(ROOT_COPY):
    shutil.copy(ROOT_COPY, NEGATED_DATA_PATH)
    print(f"Copied {ROOT_COPY} → {NEGATED_DATA_PATH}")

if not os.path.exists(NEGATED_DATA_PATH):
    raise FileNotFoundError(
        f"Negated dataset not found at {NEGATED_DATA_PATH}.\n"
        "Run negation_set_generation.py first (requires NVIDIA_API_KEY)."
    )

df_raw = pd.read_excel(NEGATED_DATA_PATH)
print(f"Loaded negated dataset: {len(df_raw)} rows")
print(f"Columns: {list(df_raw.columns)}")

# Columns expected: premises, hypothesis, negated_hypothesis, label
# Drop rows where negated_hypothesis was not generated
df_raw = df_raw.dropna(subset=["negated_hypothesis"])

# Exclude neutral examples (label == 1) — no well-defined negated gold label
df_raw = df_raw[df_raw["label"] != 1].copy()

# Compute negated gold label: entailment↔contradiction
def flip_label(label_int):
    return 2 if label_int == 0 else 0

df_raw["negated_label"] = df_raw["label"].apply(flip_label)
df_raw["negated_label_text"] = df_raw["negated_label"].map(LABEL_MAP)

if NUM_SAMPLES:
    df_raw = df_raw.sample(n=min(NUM_SAMPLES, len(df_raw)), random_state=42)

dataset = Dataset.from_pandas(df_raw.reset_index(drop=True))
print(f"Evaluating on {len(dataset)} negated examples (neutral excluded)")


# ── Inference helpers ─────────────────────────────────────────────────────────
def load_model_and_tokenizer(model_path_or_name: str):
    print(f"\nLoading model: {model_path_or_name}")
    tok = AutoTokenizer.from_pretrained(model_path_or_name, trust_remote_code=True)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    tok.padding_side = "left"
    mdl = AutoModelForCausalLM.from_pretrained(
        model_path_or_name,
        trust_remote_code=True,
        torch_dtype=torch.bfloat16,
        device_map="auto",
    )
    mdl.eval()
    mdl.config.use_cache = True
    print(f"  Parameters: {mdl.num_parameters() / 1e6:.1f}M")
    return mdl, tok


def predict_batch(model, tokenizer, premises, neg_hypotheses):
    # Prompt uses the NEGATED hypothesis
    prompts = [
        f"Premis: {p}. Hypothesis: {h}. Label:"
        for p, h in zip(premises, neg_hypotheses)
    ]
    inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=MAX_LENGTH,
    ).to(model.device)

    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=5,
            do_sample=False,
            temperature=1.0,
            pad_token_id=tokenizer.pad_token_id,
        )

    preds = []
    for seq in out:
        new_tokens = seq[inputs["input_ids"].shape[1]:]
        text = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()
        first_word = text.split()[0] if text.split() else ""
        if first_word in VALID_LABELS:
            preds.append(first_word)
        else:
            matched = next((l for l in VALID_LABELS if l in text), "unknown")
            preds.append(matched)
    return preds


def run_evaluation(model, tokenizer, dataset, label: str) -> pd.DataFrame:
    rows = []
    n = len(dataset)
    print(f"\nEvaluating [{label}] on {n} negated examples …")
    for start in range(0, n, INFER_BATCH_SIZE):
        end = min(start + INFER_BATCH_SIZE, n)
        batch = dataset.select(range(start, end))
        premises        = batch["premises"]
        orig_hyps       = batch["hypothesis"]
        neg_hyps        = batch["negated_hypothesis"]
        orig_labels     = [LABEL_MAP[l] for l in batch["label"]]
        gold_neg_labels = batch["negated_label_text"]
        predicted       = predict_batch(model, tokenizer, premises, neg_hyps)
        for p, oh, nh, ol, gl, pr in zip(
            premises, orig_hyps, neg_hyps, orig_labels, gold_neg_labels, predicted
        ):
            rows.append({
                "premise":                 p,
                "original_hypothesis":     oh,
                "negated_hypothesis":      nh,
                "original_label":          ol,
                "correct_label_negated":   gl,
                "predicted_label":         pr,
            })
        if (start // INFER_BATCH_SIZE) % 20 == 0:
            print(f"  {end}/{n} done …")
    df = pd.DataFrame(rows)
    acc = (df["correct_label_negated"] == df["predicted_label"]).mean()
    print(f"  Accuracy on negated set: {acc:.4f} ({acc * 100:.2f}%)")
    return df


# ── Baseline ──────────────────────────────────────────────────────────────────
base_model, base_tok = load_model_and_tokenizer(BASE_MODEL_NAME)
df_base = run_evaluation(base_model, base_tok, dataset, "baseline")
out_base = os.path.join(RESULTS_DIR, "negation-baseline.xlsx")
df_base.to_excel(out_base, index=False)
print(f"Saved: {out_base}")

del base_model
torch.cuda.empty_cache()


# ── Fine-tuned model ──────────────────────────────────────────────────────────
if not os.path.exists(FINETUNED_DIR):
    print(f"\nFine-tuned model not found at {FINETUNED_DIR} — skipping.")
else:
    ft_model, ft_tok = load_model_and_tokenizer(FINETUNED_DIR)
    df_ft = run_evaluation(ft_model, ft_tok, dataset, "finetuned")
    out_ft = os.path.join(RESULTS_DIR, "negation-finetuned.xlsx")
    df_ft.to_excel(out_ft, index=False)
    print(f"Saved: {out_ft}")
    del ft_model
    torch.cuda.empty_cache()

print("\nDone.")
